version: "3"

services:
  node:
    build:
      context: ./
      args:
        WORKSPACE: "wallpaper_system"
    image: "wallpaper_system/node:latest"
    ports:
      - "3456:3000"
    volumes:
      - "./:/wallpaper_system"
    command: bash -c "npm install && npm run server"
  watch:
    image: node:14
    working_dir: /wallpaper_system
    volumes:
      - "./:/wallpaper_system"
    command:  bash -c "npm install && npm run watch"

